[env]
# this forces alacritty to use standard scaling
# it fixes auto-scaling font issues which make the characters massive on high
# resolution displays.
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "None"
dynamic_title = true
startup_mode = "Windowed"
# not working with my i3 configuration, may look at this at some point in the future.
# opacity = 0.93

[scrolling]
history = 10000

[font]
size = 11.5

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 500
thickness = 0.15

[colors]
# Tokyo Night inspired
[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[colors.normal]
black =   "#32344a"
red =     "#f7768e"
green =   "#9ece6a"
yellow =  "#e0af68"
blue =    "#7aa2f7"
magenta = "#bb9af7"
cyan =    "#7dcfff"
white =   "#a9b1d6"

[terminal.shell]
program = "/usr/bin/fish"

[selection]
save_to_clipboard = false
